version: '3'

services:
  # 此镜像仅用于测试 正式环境需自行安装数据库
  # SID: XE user: system password: oracle
  oracle:
    image: tekintian/oracle12c:latest
    container_name: oracle
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      DBCA_TOTAL_MEMORY: 16192
    ports:
      - "18080:8080"
      - "1521:1521"
    volumes:
      # 数据挂载
      - "/docker/oracle/data:/u01/app/oracle"
    restart: always
